name: QA environment static web sever deploy

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

env:
  BUCKET_NAME : ${{ secrets.QA_BUCKET_NAME }}
  AWS_REGION : ap-northeast-2

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: git clone the repository
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.IAM_ROLE }}

      - name: move project
        run : cd react-deploy-sample

      - name: build
        working-directory: ./react-deploy-sample
        run: |
          yarn
          yarn build

      - name: deploy static site to s3 bucket
        working-directory: ./react-deploy-sample
        run: aws s3 sync ./build/ s3://${{ env.BUCKET_NAME }} --delete